ansible_python_interpreter: "/usr/bin/python3.12"

domain: "chat.newt239.dev"
caddy_email: "contact@newt239.dev"

postgres:
  user: "postgres"
  db: "chat"

cors_allowed_origins: "https://chat.newt239.dev"

wasabi:
  region: "ap-northeast-1"
  endpoint: "https://ap-northeast-1.s3.wasabisys.com"
